import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h1">
        starter project with next, material ui and web3
      </Typography>
      <Typography variant="h4">packages installtation:</Typography>
      <Typography variant="h4">----------</Typography>
      <Typography variant="h4">
        npx create-next-app@latest project-name
      </Typography>
      <Typography variant="h4">
        yarn add @mui/material @mui/icons-material @mui/lab@emotion/react
        @emotion/styled
      </Typography>
      <Typography variant="h4">
        yarn add @emotion/cache @emotion/server
      </Typography>
      <Typography variant="h4">yarn add ipfs-http-client</Typography>
      <Typography variant="h4">
        yarn add @rainbow-me/rainbowkit wagmi ethers@^5
      </Typography>
      <Typography variant="h4">yarn add @apollo/client graphql</Typography>
      <Typography variant="h4">????yarn add swr</Typography>
      <Typography variant="h4">
        {" "}
        Then check out. How to guilde to server side rendering --
        https://mui.com/material-ui/guides/server-rendering/{" "}
      </Typography>
      <Typography variant="h4">
        and. copy from github
        https://github.com/mui/material-ui/tree/HEAD/examples/material-next
      </Typography>
      <Typography variant="h4">
        Read GraphQL: https://www.apollographql.com/docs/react/get-started
      </Typography>
      <Typography variant="h4">
        Read how to add Web3 Wallet:
        https://www.rainbowkit.com/docs/installation
      </Typography>
      <Typography variant="h4">
        Read Web3 Interaction: https://wagmi.sh/core/getting-started
      </Typography>
      <Typography variant="h4">
        Read IPFS API: Reference dabit's project for create-nft.js in
        https://github.com/dabit3/polygon-ethereum-nextjs-marketplace/
      </Typography>
      <Typography variant="h4">
        ????SWR for data fetching https://swr.vercel.app/docs/getting-started
      </Typography>
      <Typography variant="h4">
        https://mui.com/material-ui/getting-started/templates/
      </Typography>
    </>
  );
}
