import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h1">
        starter project with next and material ui
      </Typography>
      <Typography variant="h4">packages installtation:</Typography>
      <Typography variant="h4">----------</Typography>
      <Typography variant="h4">
        npx create-next-app@latest project-name
      </Typography>
      <Typography variant="h4">
        yarn add @mui/material @emotion/react @emotion/styled
      </Typography>
      <Typography variant="h4">
        yarn add @emotion/cache @emotion/server
      </Typography>
      <Typography variant="h4">
        {" "}
        Then check out. How to guilde to server side rendering --
        https://mui.com/material-ui/guides/server-rendering/{" "}
      </Typography>
      <Typography variant="h4">
        and. copy from github
        https://github.com/mui/material-ui/tree/HEAD/examples/material-next
      </Typography>
    </>
  );
}
